583final/WebApplication5/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    [OutputCache(CacheProfile = "StaticUser")]
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ViewOrder()
        {
            return View();
        }
    }
}

583final/WebApplication5/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication5.Controllers
{
    [OutputCache(CacheProfile = "StaticUser")]
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddProduct()
        {
            return View();
        }
        public ActionResult ViewProduct()
        {
            return View();
        }
    }
}

583final/WebApplication5/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Helper;
using System.Security.Claims;
using Microsoft.Owin.Security;
using WebApplication5.Models;
using System.Configuration;

namespace WebApplication5.Controllers
{
    [OutputCache(CacheProfile = "StaticUser")]
    public class ShoppingCartController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ManageShoppingCart2()
        {
            return View();
        }
        public ActionResult CheckOutSummary()
        {
            return View();
        }
        public ActionResult InitiateCreditTransaction()
        {
            //Assign the values for the properties we need to pass to the service
            String AppId = ConfigurationManager.AppSettings["CreditAppId"];
            String SharedKey = ConfigurationManager.AppSettings["CreditAppSharedKey"];
            String AppTransId = "3";
           // String MemberType = Request.Form["membershipOptions"];
            String AppTransAmount = Request.Form["paymentName"];


            // Hash the values so the server can verify the values are original
            String hash = HttpUtility.UrlEncode(CreditAuthorizationClient.GenerateClientRequestHash(SharedKey, AppId, AppTransId, AppTransAmount));

            //Create the URL and  concatenate  the Query String values
            String url = "http://ectweb2.cs.depaul.edu/ECTCreditGateway/Authorize.aspx";
            url = url + "?AppId=" + AppId;
            url = url + "&TransId=" + AppTransId;
            url = url + "&AppTransAmount=" + AppTransAmount;
            url = url + "&AppHash=" + hash;

            return Redirect(url);
        }

        public ActionResult ProcessCreditResponse(String TransId, String TransAmount, String StatusCode, String AppHash)
        {
            String AppId = ConfigurationManager.AppSettings["CreditAppId"];
            String SharedKey = ConfigurationManager.AppSettings["CreditAppSharedKey"];
            String MembershipType = "";
            if (TransId == "2")
            { MembershipType = "GoldenMember"; }
            else if (TransId == "1")
            {
                MembershipType = "SilverMember";
            }
            if (Helper.CreditAuthorizationClient.VerifyServerResponseHash(AppHash, SharedKey, AppId, TransId, TransAmount, StatusCode))
            {
                switch (StatusCode)
                {
                    case ("A"):
                        {
                            if (TransId == "3")
                            {
                                ViewBag.TransactionStatus = "Transaction Approved! Your Order will be processed ASAP.";
                                using (ApplicationContext context = new ApplicationContext())
                                {
                                   String currentUserId = ((ClaimsIdentity)this.User.Identity).Claims
                           .Where(c => c.Type == ClaimTypes.NameIdentifier)
                           .Select(c => c.Value).ToList().LastOrDefault();
                                    List<ShoppingCartItem> shoppingCart = null;
                                    shoppingCart = context.ShoppingCart.Select(t => new ShoppingCartItem
                                    {
                                        productId = t.productId,
                                        numbers = t.numbers,
                                        userId = t.userId

                                    }).Where(t => t.userId.Equals(currentUserId)).ToList();
                                    if (shoppingCart != null && shoppingCart.Count != 0)
                                    {
                                        for (int i = 0; i < shoppingCart.Count; i++)
                                        {

                                            ShoppingCartItem shoppingCartItem = context.ShoppingCart.Find(currentUserId, shoppingCart.ElementAt(i).productId);
                                            context.ShoppingCart.Remove(shoppingCartItem);

                                            context.SaveChanges();
                                        }


                                    }





                                }
                            }
                            else
                            {
                                ViewBag.TransactionStatus = "Transaction Approved! Thanks for upgrade your membership. We will provide the best service for you.";


                                using (ApplicationContext context = new ApplicationContext())
                                {



                                    var AuthenticationManager = HttpContext.GetOwinContext().Authentication;
                                    var Identity = new ClaimsIdentity(User.Identity);
                                    String role = ((ClaimsIdentity)this.User.Identity).Claims
                                                                  .Where(c => c.Type == ClaimTypes.Role)
                                                                  .Select(c => c.Value).First();
                                    // Identity.RemoveClaim(new Claim(ClaimTypes.Role, role));

                                    Identity.AddClaim(new Claim(ClaimTypes.Role, MembershipType));
                                    AuthenticationManager.AuthenticationResponseGrant = new AuthenticationResponseGrant(new ClaimsPrincipal(Identity), new AuthenticationProperties { IsPersistent = true });
                                }
                            }

                            break;
                        }
                    case ("D"): { ViewBag.TransactionStatus = "Transaction Denied! Sorry,try again or contanct customer service"; break; }
                    case ("C"): { ViewBag.TransactionStatus = "Transaction Cancelled!"; break; }

                }
            }
            else
            {
                ViewBag.TransactionStatus = "Hash Verification failed... something went wrong.";
            }

            return View();
        }
    }
}

583final/WebApplication5/Views/Shared/BrowseProduct.cshtml
@using ExtensionHelpers
@model WebApplication5.Models.Product
<div id="CategoryContainer">
    <h4 class="modal-title">Choose Product Type</h4>
    <Select id="category" onchange="category_click();">
        <option value="All">All</option>
        <option value="Special Collection Wine">Special Collection Wine</option>
        <option value="Ancient Wine">Ancient Wine</option>
        <option value="Regular Wine">Regular Wine</option>
    </Select>
    <br>
    <br>
</div>

<h4>Product Information</h4>
<div id="ProductsContainer">

</div>


@section Scripts
{
    <script type="text/javascript">
        var pc="";

        var currentUser = {};
        var membership = "membership";
        var userId = "userId";


        $(document).ready(function () {


           pc = document.getElementById('category').value;
           getCurrrentUserRole();


        });

        function category_click() {

             pc = document.getElementById('category').value;


           getCurrrentUserRole();

        }

        function addToShoppingCart(productId) {

            $.ajax({
                url: '/api/ShoppingCart/?productId=' + productId + "&currentUserId=" + currentUser[userId],
                type: 'POST',

                success: function (result) {
                   alert("Add to shopping cart.")
                },
                error: function (result) {
                    alert("Unable to add to shopping cart.")
                }
            });
        }
        function getCurrrentUserRole() {
            $.getJSON("/api/Role/", function (data) {
                console.log(data);
                $.each(data, function (i, cUser) {
                    console.log(cUser);
                    console.log(cUser.Role);
                    currentUser[membership] = cUser.Role;
                    currentUser[userId] = cUser.UserId;
                });
                loadProducts(pc, currentUser[membership]);

            });

        }

         function loadProducts(category, memberCategory) {

             $("#ProductsContainer").empty();
             $.ajax({
                 url: '/api/Product?category=' + category + '&MemberCategory=' + memberCategory,
                 type: 'GET',
                 success: function (data) {
                     $.each(data, function (i, product) {
                         $("#ProductsContainer").append("<div id='" + product.Id + "' class='panel panel-default'><div class='panel-heading'><h3 class='panel-title' > Product Name : " + product.Name + "</h3></div><div class='panel-body'>Product Description : " + product.Description + "</div>"
                             + "<div class='panel-body'>Product Price : " + product.UnitPrice + "</div>" + "<div class='panel-body'>Product Category : " + product.Category + "</div></div>");
                         if (memberCategory != "Admin") {
                             $("#" + product.Id + " div:nth-child(4)").append("<span style='float:right;'><a class='btn btn-danger' href='javascript:addToShoppingCart(" + product.Id + ");'> Add to Shopping Cart</a></span>");
                         }

                     });

                 },
                 error: function (result) {
                     alert("Unable to load product.")
                 }
             });

         }


    </script>
}

583final/WebApplication5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Best Wine", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                   
                    @if (this.User.IsInRole("Admin")&&!this.User.IsInRole("RegularMember") && !this.User.IsInRole("SilverMember") &&! this.User.IsInRole("GoldenMember"))
                    {
                     <li>@Html.ActionLink("Manage Product", "AddProduct", "Product")</li>}
                    @if (this.User.IsInRole("Admin") || this.User.IsInRole("RegularMember") || this.User.IsInRole("SilverMember") || this.User.IsInRole("GoldenMember"))
                    {
                        <li>@Html.ActionLink("View Product", "ViewProduct", "Product")</li>
                    }
                    @if (!this.User.IsInRole("Admin")&&( this.User.IsInRole("RegularMember") ||this.User.IsInRole("SilverMember") || this.User.IsInRole("GoldenMember")))
                    {
                        <li>@Html.ActionLink("Membership", "ViewMembership", "Membership")</li>
                        <li>@Html.ActionLink("Shopping Cart", "ManageShoppingCart2", "ShoppingCart")</li>
                        <li>@Html.ActionLink("View Order", "ViewOrder", "Order")</li>

                    }
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>